# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      UNS_mqtt.host: "localhost"
      UNS_mqtt.port: 1883
      UNS_graphdb.url: "bolt://localhost:7687"
      UNS_graphdb.username: "neo4j"
      UNS_graphdb.password: $(openssl rand -base64 32 | tr -dc '[:alnum:]')
      test_variable: "Hello World"
    services:
      uns_mqtt:
        image: emqx/emqx:latest
        ports:
          - "1883:1883"
          - "8083:8083"
      uns_graphdb:
        image: neo4j:latest
        ports:
          - "7474:7474"
          - "7687:7687"
        env: 
          NEO4J_AUTH: neo4j/${{ env.UNS_graphdb.password }}
          apoc.export.file.enabled: true
          apoc.import.file.enabled: true
          apoc.import.file.use_neo4j_config: true
          NEO4J_PLUGINS: '["apoc"]'
    steps:
      - id: test_service
        run: |
          echo "The value of the test_variable is: ${{ env.test_variable }}"
          echo "-----------------------------------------------"
          echo "${{ env.UNS_graphdb.url }} ${{ env.UNS_mqtt.port }} ${{ env.UNS_mqtt.host }}"
          
          echo "env.UNS_graphdb.url: $UNS_graphdb__url"
          echo "env.UNS_graphdb.url: $UNS_graphdb_url"
          
          echo "-----------------------------------------------"

          nc -zv localhost 7687
          nc -zv localhost 1883
          
          nc -zv uns_graphdb 7687       
          nc -zv uns_mqtt  1883
          
          netstat -ntpl
          ifconfig
          docker ps
          env          

