name: Create Pull Request
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Provide Tag name"
        type: text
        default: "v1.0.0-beta"

jobs:
  create-branch: 
    name: Create Branch
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.commit_new_version.outputs.branch_name }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create Random File
        run: |
          RANDOM=$(openssl rand -base64 32 | tr -dc '[:alnum:]')
          echo "Random Text: $RANDOM" >> random.txt
          
      - id: commit_new_version
        name: Commit and push modified files
        run: |
          MODIFIED_FILES=$(git diff --name-only HEAD)
          if [ -z "$MODIFIED_FILES" ]; then
            echo "No changes to commit."
          else
            git config --global user.email "actions@github.com"
            git config --global user.name "Github Actions"
            git add .
            BRANCH_NAME="${{ inputs.tag_name}}"
            git checkout -b $BRANCH_NAME
            git commit -m "Creating new branch: $BRANCH_NAME "
            git push origin $BRANCH_NAME
          fi
          
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT
  
  create_pull_req:
    name: Create Pull Request
    runs-on: ubuntu-latest
    needs: create-branch
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Reset promotion branch
        run: |
          git fetch origin main
          git reset --hard main
          
      - name: Raise Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Creating Pull Request"
          body: "This is a Pull Request to update version of artifacts"
          labels: "version-update"
          branch: "${{ needs.create-branch.outputs.branch_name }}"
          base: main
